# Build image
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
# Изменяем текущий каталог в контейнере 
WORKDIR /app

COPY ./Server/Server.csproj ./
# Восстановление зависимостей указанных в файле проекта
RUN dotnet restore

COPY . ./
RUN dotnet publish ./Server/Server.csproj -c Release -o out

# Runtime image
FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Server.dll"]
