version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: server_postgres
    restart: always
    env_file:
      - postgres.env
    ports:
      - "35432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
       
  seq:
    image: datalust/seq
    container_name: seq
    restart: always
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - ./var/seq:/data
    ports:
        - 35341:5341
        - 7010:80

  web:
    depends_on:
      - postgres
    container_name: web
    restart: always
    image: web_image:1
    ports:
      - "7000:5000"
    env_file:
      - web.env

volumes:
  pg_data:
  seq_data:
