version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: server_postgres
    restart: always
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
       
  seq:
    image: datalust/seq
    container_name: seq
    restart: always
    environment: # принимаю условия лицензионного соглашения
      - ACCEPT_EULA=Y
    ports:
      - 5431:5431
      - 7010:80
    volumes:
      - seq_data:/var/seq/data

  web:
    depends_on:
      - postgres
    container_name: web
    restart: always
    image: web_image:1
    ports:
      - "7000:5000"
    env_file:
      - web.env

volumes:
  pg_data:
  seq_data:
