version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: server_postgres
    restart: always
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
      
  server:
    depends_on:
      - postgres
    container_name: server
    restart: always
    image: server_image:1
    env_file:
      - server.env



volumes:
  pg_data: