// <auto-generated />
using System;
using DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataBase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211113122310_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DataBase.Entities.BlackjackHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Bid")
                        .HasColumnType("double precision")
                        .HasColumnName("bid");

                    b.Property<int>("DialerScope")
                        .HasColumnType("integer")
                        .HasColumnName("dialer_scope");

                    b.Property<int>("GameState")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("UserScope")
                        .HasColumnType("integer")
                        .HasColumnName("user_scope");

                    b.HasKey("Id");

                    b.HasIndex("Bid")
                        .HasDatabaseName("IX_blackjack_history_bid");

                    b.HasIndex("DialerScope")
                        .HasDatabaseName("IX_blackjack_history_dialer_scope");

                    b.HasIndex("GameState")
                        .HasDatabaseName("IX_blackjack_history_state");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_blackjack_history_user_id");

                    b.HasIndex("UserScope")
                        .HasDatabaseName("IX_blackjack_history_user_scope");

                    b.ToTable("blackjack_history");
                });

            modelBuilder.Entity("DataBase.Entities.RouletteHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Coin")
                        .HasColumnType("double precision")
                        .HasColumnName("coin");

                    b.Property<int>("GameState")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Coin")
                        .HasDatabaseName("IX_roulette_history_coin");

                    b.HasIndex("GameState")
                        .HasDatabaseName("IX_roulette_history_state");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_roulette_history_user_id");

                    b.ToTable("roulette_history");
                });

            modelBuilder.Entity("DataBase.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<DateTime>("LastAction")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_action");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("IX_users_firstname");

                    b.HasIndex("LastAction")
                        .HasDatabaseName("IX_users_last_action");

                    b.HasIndex("LastName")
                        .HasDatabaseName("IX_users_lastname");

                    b.HasIndex("Nickname")
                        .HasDatabaseName("IX_users_nickname");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_users_phone_number");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DataBase.Entities.UserStateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Balance")
                        .HasColumnType("double precision")
                        .HasColumnName("balance");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("UserStateType")
                        .HasColumnType("integer")
                        .HasColumnName("state_type");

                    b.HasKey("Id");

                    b.HasIndex("Balance")
                        .HasDatabaseName("IX_users_state_balance");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_users_state_user_id");

                    b.HasIndex("UserStateType")
                        .HasDatabaseName("IX_users_state_state_type");

                    b.ToTable("users_state");
                });
#pragma warning restore 612, 618
        }
    }
}
